# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/14bmkelley/Desktop/cpe233/Exp7/cpu/cpu.cache/wt [current_project]
set_property parent.project_path C:/Users/14bmkelley/Desktop/cpe233/Exp7/cpu/cpu.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/Users/14bmkelley/Desktop/cpe233/Exp7/cpu/cpu.srcs/sources_1/new/StackPointer.vhd
read_xdc C:/Users/14bmkelley/Desktop/cpe233/Exp7/cpu/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/14bmkelley/Desktop/cpe233/Exp7/cpu/Basys3_Master.xdc]

synth_design -top StackPointer -part xc7a35tcpg236-1
write_checkpoint -noxdef StackPointer.dcp
catch { report_utilization -file StackPointer_utilization_synth.rpt -pb StackPointer_utilization_synth.pb }
